services:
  wch_db:
    build:
      context: docker/db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  wch:
    build:
      context: .
    restart: always
    depends_on:
      wch_db:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@wch_db:5432/db
    env_file:
      - .env

volumes:
  db-data:
    driver: local
